var choliList = [
  {
    'image': 'https://rangoliindia.com/uploads/10_Rang_0286.jpg',
    'image type 1':'https://rangoliindia.com/uploads/10.Rang_0288.jpg',
    'image type 2':'https://rangoliindia.com/uploads/10.Rang_0289.jpg',
    'image type 3':'https://rangoliindia.com/uploads/10.Rang_0293.jpg',
    'image type 4':'https://rangoliindia.com/uploads/10.Rang_0295.jpg',
    'title': 'Bottle Green Designer Lehenga',
    'price': '₹6,400',
    'color': 'Bottle Green',
  },
  {
    'image': 'https://rangoliindia.com/uploads/4005_3.jpg',
    'image type 1':'https://rangoliindia.com/uploads/4005_3.jpg',
    'image type 2':'https://rangoliindia.com/uploads/4005_3.jpg',
    'image type 3':'https://rangoliindia.com/uploads/4005_3.jpg',
    'image type 4':'https://rangoliindia.com/uploads/4005_3.jpg',
    'title': 'Magenta And Feroji Color Silk Lehenga With Dupatta',
    'price': '₹8,400',
    'color': 'Magenta And Feroji',
  },
  {
    'image': 'https://rangoliindia.com/uploads/7_Rang-0835.JPG',
    'image type 1':'https://rangoliindia.com/uploads/7%20Rang-0837.JPG',
    'image type 2':'https://rangoliindia.com/uploads/7%20Rang-0838.JPG',
    'image type 3':'https://rangoliindia.com/uploads/7%20Rang-0843.JPG',
    'image type 4':'https://rangoliindia.com/uploads/7_Rang-0835.JPG',
    'title': 'White Designer Lehenga',
    'price': '₹6,400',
    'color': 'White',
  },
  {
    'image': 'https://rangoliindia.com/uploads/7_Rang-0864.JPG',
    'image type 1':'https://rangoliindia.com/uploads/7%20Rang-0865.JPG',
    'image type 2':'https://rangoliindia.com/uploads/7%20Rang-0866.JPG',
    'image type 3':'https://rangoliindia.com/uploads/7%20Rang-0867.JPG',
    'image type 4':'https://rangoliindia.com/uploads/7_Rang-0864.JPG',
    'title': 'Turquoise Green Designer Lehenga',
    'price': '₹5,320',
    'color': 'Turquoise Green',
  },
  {
    'image': 'https://rangoliindia.com/uploads/2884_3.jpg',
    'image type 1':'https://rangoliindia.com/uploads/2884_3.jpg',
    'image type 2':'https://rangoliindia.com/uploads/2884_3.jpg',
    'image type 3':'https://rangoliindia.com/uploads/2884_3.jpg',
    'image type 4':'https://rangoliindia.com/uploads/2884_3.jpg',
    'title': 'Mustard And Green Color Silk Suit Skirt With Jacket',
    'price': '₹6,480',
    'color': 'Mustard And Green',
  },
  {
    'image': 'https://rangoliindia.com/uploads/8_Rang_0478.jpg',
    'image type 1':'https://rangoliindia.com/uploads/8.Rang_0480.jpg',
    'image type 2':'https://rangoliindia.com/uploads/8.Rang_0481.jpg',
    'image type 3':'https://rangoliindia.com/uploads/8.Rang_0484.jpg',
    'image type 4':'https://rangoliindia.com/uploads/8.Rang_0485.jpg',
    'title': 'Off-white Sharara Suit Set',
    'price': '₹3040',
    'color': 'Off-white',
  },
  {
    'image': 'https://rangoliindia.com/uploads/DSC_0899_copy.jpg',
    'image type 1':'https://rangoliindia.com/uploads/DSC_0891%20copy.jpg',
    'image type 2':'https://rangoliindia.com/uploads/DSC_0892%20copy.jpg',
    'image type 3':'https://rangoliindia.com/uploads/DSC_0880%20copy.jpg',
    'image type 4':'https://rangoliindia.com/uploads/DSC_0888%20copy.jpg',
    'title': 'Mint Green Sharara Suit Set',
    'price': '₹6,280',
    'color': 'Mint Green',
  },
  {
    'image': 'https://rangoliindia.com/uploads/7_Rang-0665.JPG',
    'image type 1':'https://rangoliindia.com/uploads/7%20Rang-0667.JPG',
    'image type 2':'https://rangoliindia.com/uploads/7%20Rang-0668.JPG',
    'image type 3':'https://rangoliindia.com/uploads/7%20Rang-0670.JPG',
    'image type 4':'https://rangoliindia.com/uploads/7_Rang-0665.JPG',
    'title': 'Tuscan Yellow Sharara Set',
    'price': '₹2,520',
    'color': 'Tuscan Yellow',
  },
  {
    'image': 'https://rangoliindia.com/uploads/7_Rang-0772.JPG',
    'image type 1':'https://rangoliindia.com/uploads/7_Rang-0772.JPG',
    'image type 2':'https://rangoliindia.com/uploads/7_Rang-0772.JPG',
    'image type 3':'https://rangoliindia.com/uploads/7_Rang-0772.JPG',
    'image type 4':'https://rangoliindia.com/uploads/7_Rang-0772.JPG',
    'title': 'Mustard Sharara Suit Set',
    'price': '₹6,000',
    'color': 'Mustard',
  },
  {
    'image': '',
    'image type 1':'',
    'image type 2':'',
    'image type 3':'',
    'image type 4':'',
    'title': '',
    'price': '₹6,400',
    'color': '',
  },

];